INSERT INTO users (name, age) VALUES ('Bob', 20);
INSERT INTO users (name, age) VALUES ('Bob', 20);
INSERT INTO users (name, age) VALUES ('Sam', 21);
INSERT INTO users (name, age) VALUES ('Joel', 19);
INSERT INTO users (name, age) VALUES ('Ed', 30);
INSERT INTO users (name, age) VALUES ('Buddy', 24);
INSERT INTO users (name, age) VALUES ('Eric', 20);
INSERT INTO users (name, age) VALUES ('Jacob', 45);
INSERT INTO users (name, age) VALUES ('Josh', 22);
INSERT INTO users (name, age) VALUES ('Leah', 21);
INSERT INTO users (name, age) VALUES ('Anna', 86);
INSERT INTO users (name, age) VALUES ('Belle', 45);
INSERT INTO users (name, age) VALUES ('Boy', 50);
INSERT INTO users (name, age) VALUES ('Buggy', 15);
INSERT INTO users (name, age) VALUES ('Erica', 91);
INSERT INTO users (name, age) VALUES ('Stephanie', 28);
INSERT INTO users (name, age) VALUES ('Samuel', 27);
INSERT INTO users (name, age) VALUES ('Tilda', 36);
INSERT INTO users (name, age) VALUES ('Ashad', 26);
INSERT INTO users (name, age) VALUES ('Ashley', 43);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Project1', 'Animals', 100, '1/1/21', '2/2/21');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Project2', 'Education', 1000, '1/1/21', '2/2/21');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Project3', 'Geography', 2000, '1/1/21', '2/2/21');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Project4', 'Environmental', 3000, '1/1/21', '2/2/21');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Project5', 'Chemistry', 1500, '1/1/21', '2/2/21');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Project6', 'Animals', 10000, '1/1/21', '2/2/21');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Project7', 'Economic', 1050, '1/1/21', '2/2/21');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Project8', 'Bio-Engineering', 1900, '1/1/21', '2/2/21');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Project9', 'Medical', 50000, '1/1/21', '2/2/21');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Project0', 'Charity', 25000, '1/1/21', '2/2/21');

INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 5, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 16, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 17, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 0);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 0);
